'use client';

import { useEffect, useState, useCallback, type ReactNode } from 'react';
import Link from 'next/link';
import { Settings, Check, X, Loader2, ArrowLeft, KeyRound } from 'lucide-react';

interface MaskedConfig {
  paths: { musicDirectory: string | null; brainfuckRepo: string; pythonBin: string };
  services: {
    jellyfin: { baseUrl: string; apiKey: string | null } | null;
    transmission: { rpcUrl: string; username: string; password: string | null } | null;
    slskd: { baseUrl: string; apiKey: string | null; autoIngest: boolean } | null;
  };
  riot: { apiKey: string | null; gameName: string; tagLine: string; region: string } | null;
  minecraftServers: { name: string; host: string; port: number; password: string | null }[];
  setupTokenSet: boolean;
  postgres: { host: string; port: number; database: string };
}

interface ProjectStatus {
  slug: string;
  ready: boolean;
  missing: string[];
  setupAnchor: string | null;
}

interface ConfigResp {
  config: MaskedConfig;
  projects: Record<string, ProjectStatus>;
}

const TOKEN_KEY = 'workshop-setup-token';

export default function SetupPage() {
  const [data, setData] = useState<ConfigResp | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [token, setToken] = useState<string>('');

  useEffect(() => {
    setToken(localStorage.getItem(TOKEN_KEY) ?? '');
  }, []);

  const refresh = useCallback(async () => {
    try {
      const r = await fetch('/api/config', { cache: 'no-store' });
      if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
      const j = await r.json();
      setData(j);
      setError(null);
    } catch (e) {
      setError((e as Error).message);
    }
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  function saveToken(v: string) {
    setToken(v);
    if (v) localStorage.setItem(TOKEN_KEY, v);
    else   localStorage.removeItem(TOKEN_KEY);
  }

  async function patch(body: Record<string, unknown>): Promise<{ ok: boolean; error?: string }> {
    if (!token) return { ok: false, error: 'enter setup token first' };
    const r = await fetch('/api/config', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', 'X-Setup-Token': token },
      body: JSON.stringify(body),
    });
    const j = await r.json();
    if (!r.ok) return { ok: false, error: j.error ?? `${r.status}` };
    await refresh();
    return { ok: true };
  }

  if (error) {
    return (
      <div className="p-8 max-w-3xl mx-auto">
        <div className="rounded-lg border border-red-500/30 bg-red-500/5 p-4 text-red-300">{error}</div>
      </div>
    );
  }
  if (!data) return <div className="p-8 text-white/40">Loading…</div>;

  return (
    <div className="p-6 md:p-10 max-w-4xl mx-auto">
      <Link href="/" className="inline-flex items-center gap-2 text-sm text-white/50 hover:text-white/80 mb-6">
        <ArrowLeft className="h-4 w-4" /> Back
      </Link>

      <div className="flex items-center gap-3 mb-2">
        <Settings className="h-6 w-6 text-cyan-400" />
        <h1 className="text-3xl font-bold">Setup</h1>
      </div>
      <p className="text-white/50 mb-8">
        Configure external services without leaving the browser. Saved values write straight to <code className="text-cyan-300">config.json</code>.
      </p>

      {/* Token */}
      <SectionCard title="Setup Token" anchor="token" icon={<KeyRound className="h-5 w-5" />}>
        <p className="text-sm text-white/50 mb-3">
          Generated by <code>npm run setup</code>. Required to save changes from this page.
          {!data.config.setupTokenSet && (
            <span className="block mt-2 text-amber-300/80">
              ⚠ <code>setupToken</code> is not set in config.json — writes are disabled. Edit it directly.
            </span>
          )}
        </p>
        <input
          type="password"
          placeholder="Paste setup token…"
          value={token}
          onChange={(e) => saveToken(e.target.value)}
          className="w-full bg-black/40 border border-white/10 rounded px-3 py-2 text-sm font-mono"
        />
      </SectionCard>

      {/* Project readiness summary */}
      <SectionCard title="Project Readiness" anchor="projects">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm">
          {Object.values(data.projects).map((s) => (
            <div key={s.slug} className="flex items-center gap-2 px-3 py-2 rounded bg-white/[0.02]">
              {s.ready
                ? <Check className="h-4 w-4 text-emerald-400 shrink-0" />
                : <X className="h-4 w-4 text-amber-400 shrink-0" />}
              <span className="font-mono text-white/70">{s.slug}</span>
              {!s.ready && (
                <span className="text-xs text-white/40 truncate" title={s.missing.join('; ')}>
                  — {s.missing[0]}
                </span>
              )}
            </div>
          ))}
        </div>
      </SectionCard>

      {/* Postgres (read-only summary; CLI bootstraps it) */}
      <SectionCard title="Postgres" anchor="postgres">
        <p className="text-xs text-white/40 mb-3">
          Managed by <code>npm run setup</code>. Edit <code>config.json</code> directly to change credentials.
        </p>
        <div className="font-mono text-sm text-white/70">
          {data.config.postgres.host}:{data.config.postgres.port}/{data.config.postgres.database}
        </div>
        <ProbeButton service="postgres" />
      </SectionCard>

      {/* Paths */}
      <SectionCard title="Paths" anchor="brainfuck">
        <PathRow
          label="BrainFuck repo"
          field="brainfuckRepo"
          value={data.config.paths.brainfuckRepo}
          probe="brainfuck"
          onSave={(v) => patch({ paths: { ...data.config.paths, brainfuckRepo: v } })}
        />
        <PathRow
          label="Python interpreter"
          field="pythonBin"
          value={data.config.paths.pythonBin}
          probe="brainfuck"
          onSave={(v) => patch({ paths: { ...data.config.paths, pythonBin: v } })}
        />
        <div id="music">
          <PathRow
            label="Music directory"
            field="musicDirectory"
            value={data.config.paths.musicDirectory ?? ''}
            probe="music"
            placeholder="/path/to/music (optional)"
            allowEmpty
            onSave={(v) => patch({ paths: { ...data.config.paths, musicDirectory: v || null } })}
          />
        </div>
      </SectionCard>

      {/* slskd */}
      <ServiceCard
        title="slskd (Soulseek)"
        anchor="slskd"
        probe="slskd"
        present={data.config.services.slskd != null}
        fields={[
          { key: 'baseUrl', label: 'Base URL', value: data.config.services.slskd?.baseUrl ?? '' },
          { key: 'apiKey', label: 'API Key', value: '', placeholder: data.config.services.slskd?.apiKey ?? '(set)', secret: true },
          { key: 'autoIngest', label: 'Auto-ingest', value: String(data.config.services.slskd?.autoIngest ?? false), kind: 'bool' },
        ]}
        onSave={(values) => {
          const cur = data.config.services.slskd;
          const next = {
            baseUrl: String(values.baseUrl ?? cur?.baseUrl ?? ''),
            apiKey: values.apiKey ? String(values.apiKey) : (cur?.apiKey ?? ''),
            autoIngest: values.autoIngest === 'true',
          };
          return patch({ services: { ...data.config.services, slskd: next } });
        }}
        onClear={() => patch({ services: { ...data.config.services, slskd: null } })}
      />

      {/* transmission */}
      <ServiceCard
        title="Transmission"
        anchor="transmission"
        probe="transmission"
        present={data.config.services.transmission != null}
        fields={[
          { key: 'rpcUrl', label: 'RPC URL', value: data.config.services.transmission?.rpcUrl ?? 'http://127.0.0.1:9091/transmission/rpc' },
          { key: 'username', label: 'Username', value: data.config.services.transmission?.username ?? '' },
          { key: 'password', label: 'Password', value: '', placeholder: data.config.services.transmission?.password ?? '(set)', secret: true },
        ]}
        onSave={(values) => {
          const cur = data.config.services.transmission;
          const next = {
            rpcUrl: String(values.rpcUrl ?? cur?.rpcUrl ?? ''),
            username: String(values.username ?? cur?.username ?? ''),
            password: values.password ? String(values.password) : (cur?.password ?? ''),
          };
          return patch({ services: { ...data.config.services, transmission: next } });
        }}
        onClear={() => patch({ services: { ...data.config.services, transmission: null } })}
      />

      {/* jellyfin */}
      <ServiceCard
        title="Jellyfin"
        anchor="jellyfin"
        probe="jellyfin"
        present={data.config.services.jellyfin != null}
        fields={[
          { key: 'baseUrl', label: 'Base URL', value: data.config.services.jellyfin?.baseUrl ?? 'http://localhost:8096' },
          { key: 'apiKey', label: 'API Key (optional)', value: '', placeholder: data.config.services.jellyfin?.apiKey ?? '', secret: true },
        ]}
        onSave={(values) => {
          const cur = data.config.services.jellyfin;
          const next = {
            baseUrl: String(values.baseUrl ?? cur?.baseUrl ?? ''),
            apiKey: values.apiKey ? String(values.apiKey) : (cur?.apiKey ?? null),
          };
          return patch({ services: { ...data.config.services, jellyfin: next } });
        }}
        onClear={() => patch({ services: { ...data.config.services, jellyfin: null } })}
      />

      {/* riot */}
      <ServiceCard
        title="Riot API"
        anchor="riot"
        probe="riot"
        present={data.config.riot != null}
        fields={[
          { key: 'apiKey', label: 'API Key', value: '', placeholder: data.config.riot?.apiKey ?? '(set)', secret: true },
          { key: 'gameName', label: 'Summoner Name', value: data.config.riot?.gameName ?? '' },
          { key: 'tagLine', label: 'Tag Line', value: data.config.riot?.tagLine ?? '' },
          { key: 'region', label: 'Region', value: data.config.riot?.region ?? 'na1' },
        ]}
        onSave={(values) => {
          const cur = data.config.riot;
          const next = {
            apiKey: values.apiKey ? String(values.apiKey) : (cur?.apiKey ?? ''),
            gameName: String(values.gameName ?? cur?.gameName ?? ''),
            tagLine: String(values.tagLine ?? cur?.tagLine ?? ''),
            region: String(values.region ?? cur?.region ?? 'na1'),
          };
          return patch({ riot: next });
        }}
        onClear={() => patch({ riot: null })}
      />

      {/* minecraft */}
      <SectionCard title={`Minecraft RCON (${data.config.minecraftServers.length})`} anchor="minecraft">
        <p className="text-xs text-white/40 mb-3">Per-server array editor; edit <code>config.json</code> directly for now.</p>
        <ul className="space-y-1 text-sm font-mono">
          {data.config.minecraftServers.map((s) => (
            <li key={s.name} className="text-white/60">
              {s.name} — {s.host}:{s.port} ({s.password ? 'pw set' : 'no pw'})
            </li>
          ))}
          {data.config.minecraftServers.length === 0 && <li className="text-white/30">No servers configured.</li>}
        </ul>
      </SectionCard>
    </div>
  );
}

// ── Subcomponents ──

function SectionCard({ title, anchor, icon, children }: {
  title: string; anchor: string; icon?: ReactNode; children: ReactNode;
}) {
  return (
    <section id={anchor} className="rounded-xl border border-white/10 bg-black/20 p-5 mb-5 scroll-mt-20">
      <div className="flex items-center gap-2 mb-4">
        {icon}
        <h2 className="text-lg font-semibold">{title}</h2>
      </div>
      {children}
    </section>
  );
}

function ProbeButton({ service }: { service: string }) {
  const [state, setState] = useState<{ status: 'idle' | 'loading' | 'ok' | 'error'; msg?: string }>({ status: 'idle' });
  async function run() {
    setState({ status: 'loading' });
    try {
      const r = await fetch(`/api/setup/probe/${service}`, { method: 'POST' });
      const j = await r.json();
      setState(j.ok
        ? { status: 'ok', msg: j.detail ?? 'OK' }
        : { status: 'error', msg: j.error ?? 'failed' });
    } catch (e) {
      setState({ status: 'error', msg: (e as Error).message });
    }
  }
  return (
    <div className="mt-3 flex items-center gap-3">
      <button onClick={run}
        className="text-xs px-3 py-1.5 rounded border border-cyan-500/40 text-cyan-300 hover:bg-cyan-500/10">
        Test connection
      </button>
      {state.status === 'loading' && <Loader2 className="h-4 w-4 animate-spin text-white/40" />}
      {state.status === 'ok' && (
        <span className="text-xs text-emerald-400 flex items-center gap-1">
          <Check className="h-3 w-3" /> {state.msg}
        </span>
      )}
      {state.status === 'error' && (
        <span className="text-xs text-rose-400 flex items-center gap-1">
          <X className="h-3 w-3" /> {state.msg}
        </span>
      )}
    </div>
  );
}

function PathRow({
  label, field, value, probe, onSave, placeholder, allowEmpty,
}: {
  label: string; field: string; value: string; probe: string;
  onSave: (v: string) => Promise<{ ok: boolean; error?: string }>;
  placeholder?: string; allowEmpty?: boolean;
}) {
  const [v, setV] = useState(value);
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  useEffect(() => { setV(value); }, [value]);

  async function save() {
    if (!allowEmpty && !v.trim()) { setErr('required'); return; }
    setSaving(true); setErr(null);
    const r = await onSave(v.trim());
    setSaving(false);
    if (!r.ok) setErr(r.error ?? 'failed');
  }
  return (
    <div className="mb-4">
      <label className="text-xs uppercase tracking-wider text-white/50 block mb-1">{label}</label>
      <div className="flex gap-2">
        <input
          name={field}
          value={v}
          placeholder={placeholder}
          onChange={(e) => setV(e.target.value)}
          className="flex-1 bg-black/40 border border-white/10 rounded px-3 py-2 text-sm font-mono"
        />
        <button onClick={save} disabled={saving}
          className="text-xs px-3 py-1.5 rounded border border-emerald-500/40 text-emerald-300 hover:bg-emerald-500/10 disabled:opacity-40">
          {saving ? '…' : 'Save'}
        </button>
      </div>
      {err && <div className="text-xs text-rose-400 mt-1">{err}</div>}
      <ProbeButton service={probe} />
    </div>
  );
}

interface FieldDef {
  key: string;
  label: string;
  value: string;
  placeholder?: string;
  secret?: boolean;
  kind?: 'text' | 'bool';
}

function ServiceCard({
  title, anchor, probe, present, fields, onSave, onClear,
}: {
  title: string; anchor: string; probe: string; present: boolean; fields: FieldDef[];
  onSave: (values: Record<string, string>) => Promise<{ ok: boolean; error?: string }>;
  onClear: () => Promise<{ ok: boolean; error?: string }>;
}) {
  const [values, setValues] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function save() {
    setSaving(true); setErr(null);
    const r = await onSave(values);
    setSaving(false);
    if (!r.ok) setErr(r.error ?? 'failed'); else setValues({});
  }

  return (
    <SectionCard title={title} anchor={anchor}>
      <div className="text-xs text-white/40 mb-3">
        {present ? '✓ configured' : 'not configured'}
      </div>
      <div className="space-y-3">
        {fields.map((f) => (
          <div key={f.key}>
            <label className="text-xs uppercase tracking-wider text-white/50 block mb-1">{f.label}</label>
            {f.kind === 'bool' ? (
              <select
                value={values[f.key] ?? f.value}
                onChange={(e) => setValues({ ...values, [f.key]: e.target.value })}
                className="bg-black/40 border border-white/10 rounded px-3 py-2 text-sm">
                <option value="false">false</option>
                <option value="true">true</option>
              </select>
            ) : (
              <input
                type={f.secret ? 'password' : 'text'}
                value={values[f.key] ?? (f.secret ? '' : f.value)}
                placeholder={f.placeholder ?? f.value}
                onChange={(e) => setValues({ ...values, [f.key]: e.target.value })}
                className="w-full bg-black/40 border border-white/10 rounded px-3 py-2 text-sm font-mono"
              />
            )}
          </div>
        ))}
      </div>
      <div className="flex gap-2 mt-4">
        <button onClick={save} disabled={saving}
          className="text-xs px-3 py-1.5 rounded border border-emerald-500/40 text-emerald-300 hover:bg-emerald-500/10 disabled:opacity-40">
          {saving ? 'Saving…' : 'Save'}
        </button>
        {present && (
          <button onClick={onClear}
            className="text-xs px-3 py-1.5 rounded border border-white/10 text-white/50 hover:bg-white/[0.03]">
            Clear
          </button>
        )}
      </div>
      {err && <div className="text-xs text-rose-400 mt-2">{err}</div>}
      <ProbeButton service={probe} />
    </SectionCard>
  );
}
